---
hosts:
  ssh:
  - name: test1
    config:
      port: 2022
      hostname: 222.239.171.72
      username: hmsfsekimyd
      password: alcls!@gozj67SE
      sudo: true
  - name: test2
    config:
      port: 2022
      hostname: 222.239.171.81
      username: hmsfsekimyd
      password: alcls!@gozj67SE
      sudo: true
  api:
#    - 192.168.64.2
#    - 192.168.64.2