---
hosts:
  - name: test1
    config:
      port: 22
      hostname: 192.168.64.2
      username: root
      password: test!@34
  - name: test2
    config:
      port: 22
      hostname: 192.168.64.2
      username: root
      password: test!@34